import { Noto_Sans_TC } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const TC = Noto_Sans_TC({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={TC.className}>
        <Header />
        <div className="px-8 lg:px-32 text-[#323232]"> {children}</div>
      </body>
    </html>
  );
}
